removed part of the workflow.

diff --git a/.github/workflows/cloudwatch_dashboard.yml b/.github/workflows/cloudwatch_dashboard.yml
--- a/.github/workflows/cloudwatch_dashboard.yml
+++ b/.github/workflows/cloudwatch_dashboard.yml
@@ -28,11 +28,11 @@ jobs:
       - name: Terraform Plan
         id: plan
         run: terraform plan  -var="candidate_id=$CANDIDATE_ID" -var="candidate_email=CANDIDATE_EMAIL" -no-color
-        continue-on-error: true
+        continue-on-error: false
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        run: exit 1
 
       - name: Terraform Apply
         if: github.ref == 'refs/heads/master' && github.event_name == 'push'
